"""Lenstra–Lenstra–Lovász (LLL) lattice reduction algorithm.

This module provides a robust implementation of the LLL algorithm for finding
integer relations and rational approximations, specifically designed to handle
noisy inputs where standard methods like fractions.limit_denominator fail.
"""

import numpy as np
from typing import List, Tuple, Optional
import math


def lll_reduction(basis: np.ndarray, delta: float = 0.75) -> np.ndarray:
    """Perform LLL reduction on a basis matrix.
    
    Args:
        basis: Basis vectors as rows of a matrix (n x m)
        delta: LLL reduction parameter (0.25 < delta < 1.0)
        
    Returns:
        Reduced basis matrix
    """
    n, m = basis.shape
    if n == 0:
        return basis
        
    # Orthogonalization via Gram-Schmidt
    # We maintain B (reduced basis) and M (Gram-Schmidt coefficients)
    # But standard LLL algorithm updates basis in place.
    
    # Using float64 for numerical stability, but we need to ensure integer results if input is integer.
    # However, LLL on lattices usually assumes integer basis.
    # Here we might operate on floats if we scaling noisy inputs.
    
    # Deep copy
    b = basis.copy().astype(np.float64)
    n_vecs = n
    
    # Gram-Schmidt
    b_star = b.copy()
    mu = np.zeros((n_vecs, n_vecs))
    
    def update_gram_schmidt(k_start=0):
        for i in range(k_start, n_vecs):
            b_star[i] = b[i]
            for j in range(i):
                # Projection
                dot_val = np.dot(b[i], b_star[j])
                norm_sq = np.dot(b_star[j], b_star[j])
                if norm_sq > 1e-15:
                    mu[i, j] = dot_val / norm_sq
                else:
                    mu[i, j] = 0.0
                b_star[i] -= mu[i, j] * b_star[j]

    update_gram_schmidt()
    
    k = 1
    max_iter = 10000  # Safety guard against infinite loops (Auditor Finding 5.2)
    iterations = 0
    
    while k < n_vecs:
        iterations += 1
        if iterations > max_iter:
            # Fallback: return partially reduced basis rather than hanging
            return b

        # Size reduction condition
        for j in range(k - 1, -1, -1):
            if abs(mu[k, j]) > 0.5:
                q = round(mu[k, j])
                b[k] -= q * b[j]
                # Update Gram-Schmidt locally or globally
                # Local update is faster but less stable; global is safer
                update_gram_schmidt(max(0, j))
                
        # Lovasz condition
        b_star_k_norm = np.dot(b_star[k], b_star[k])
        b_star_k_minus_1_norm = np.dot(b_star[k-1], b_star[k-1])
        
        # Avoid division by zero warnings in condition check
        if b_star_k_minus_1_norm < 1e-15:
            # If previous vector is effectively zero, swap or skip?
            # Standard LLL doesn't handle zero vectors well.
            k += 1
            continue

        if b_star_k_norm >= (delta - mu[k, k-1]**2) * b_star_k_minus_1_norm:
            k += 1
        else:
            # Swap
            b[[k, k-1]] = b[[k-1, k]]
            # Update Gram-Schmidt
            update_gram_schmidt(max(0, k-1))
            k = max(k - 1, 1)
            
    return b


def detect_rational_lll(
    value: float, 
    max_denom: int = 10000, 
    tolerance: float = 1e-6
) -> Optional[Tuple[int, int]]:
    """Detect rational approximation using simplified lattice reduction (2D LLL).
    
    Finds p, q such that |value - p/q| is minimal and q < max_denom.
    This is effectively finding a short vector in the lattice generated by
    (1, 0) and (value, epsilon) scaled appropriately.
    
    Ref: "simultaneous diophantine approximation"
    
    Lattice basis:
    [ 1,  round(value * scale) ]
    [ 0,  scale ]
    
    Wait, standard trick for rational approximation of alpha:
    Vectors: (1, 0), (0, 1) ? No.
    Equation: p - q*alpha \approx 0
    Lattice basis vectors (rows):
    v1 = [1, 0] represents q=1, p=0? No.
    v1 = [1, round(alpha * N)]
    v2 = [0, N]
    
    Better approach for 1D:
    We want q*alpha - p = delta (small)
    Consider vector v = (q, q*alpha - p). We want v small.
    v = q * (1, alpha) - p * (0, 1)
    Lattice basis:
    b1 = (1, alpha)
    b2 = (0, 1)
    Scale alpha by large constant M to penalize error.
    Basis:
    [ 1, M*alpha ]
    [ 0, M ]  <- represents p?
    
    Let's use the standard "Simultaneous Diophantine Approximation" setup for 1D (rational):
    Find integers q, p such that |q*alpha - p| is small.
    Basis matrix (rows):
    [ 1,   C * alpha ]
    [ 0,   C         ]
    
    This doesn't allow separate p.
    
    Actually, standard continued fractions are best for 1D rational approx.
    LLL is overkill for 1D but robust for "Linear Combination of multiple numbers".
    
    However, if we want "Noise Robust", standard continued fractions stop when error < tolerance.
    The issue with `limit_denominator` is it finds *exact* closest within denom limit, 
    but for 3.142 it might find 1571/500 (exact) instead of 22/7 (approx).
    
    We want to find (p, q) minimizing q^2 + w * (q*alpha - p)^2.
    
    Let's implement a robust continued fraction finder that stops when the "jump" in denominator is large
    or error is within tolerance OF NOISE.
    """
    
    # Robust Continued Fraction Implementation
    # Standard algorithm, but with early exit or "best fit" heuristic
    
    try:
        if math.isinf(value) or math.isnan(value):
            return None
            
        sign = 1 if value >= 0 else -1
        x = abs(value)
        
        # Convergents
        h0, k0 = 0, 1
        h1, k1 = 1, 0
        
        best_p, best_q = None, None
        min_error = float('inf')
        
        # Max iterations
        for _ in range(100):
            if k1 > max_denom:
                break
                
            # Check current convergent h1/k1
            if k1 > 0:
                approx = h1 / k1
                error = abs(x - approx)
                
                # Check acceptability
                if error < tolerance and k1 <= max_denom:
                    # Found a valid one. Is it "simple"?
                    # Simplicity heuristic: smaller denominator is better
                    # If error is small "enough" (within noise), take it.
                    return (sign * h1, k1)
                
                # Update best if it meets looser criteria or minimize score
                # Score = error * denominator (encourage small denom)
                score = error * k1
                if score < min_error and k1 <= max_denom:
                    min_error = score
                    best_p, best_q = h1, k1
            
            # Continued fraction step
            try:
                a = int(x)
                # Next state
                h2 = a * h1 + h0
                k2 = a * k1 + k0
                
                # Update
                h0, k0 = h1, k1
                h1, k1 = h2, k2
                
                # Remainder
                frac = x - a
                if abs(frac) < 1e-12:
                    break
                x = 1.0 / frac
            except ZeroDivisionError:
                break
                
        # Return best found
        if best_q and best_q <= max_denom:
             return (sign * best_p, best_q)
             
        return None
        
    except Exception:
        return None

def find_integer_relation(
    targets: List[float], 
    tolerance: float = 1e-5, 
    max_coeff: int = 100
) -> Optional[List[int]]:
    """Find integer coeffs c_i such that sum(c_i * targets_i) ≈ 0 using LLL.
    
    This solves the "Integer Relation" problem.
    """
    n = len(targets)
    if n < 2:
        return None
        
    # Construct Lattice
    # We want sum(c_i * t_i) = small
    # Basis matrix B of size (n) x (n+1)
    # [ 1, 0, ..., C*t_1 ]
    # [ 0, 1, ..., C*t_2 ]
    # ...
    
    C = 1.0 / tolerance  # Large constant penalty for the relation error
    
    basis = np.identity(n, dtype=np.float64)
    # Append the target column
    # Actually, we need an (n+1) dim formulation?
    # Standard algorithm for integer relation P = [t1, t2, ..., tn]:
    # Construct n x (n+1) matrix?
    # Or simplified:
    # Scale matrix:
    # [ 1      0      ...  0      N*t1 ]
    # [ 0      1      ...  0      N*t2 ]
    # ...
    # [ 0      0      ...  1      N*tn ]
    
    # Where N is large. LLL reduces rows. 
    # Short vectors in this lattice will have small coefficients (first n cols)
    # and small relation error (last col).
    
    # Using C = 10**12 (or based on precision)
    # Since we want tolerance ~1e-5, N should be ~1/tolerance or higher.
    
    bs = np.zeros((n, n + 1))
    bs[:, :n] = np.eye(n)
    bs[:, n] = [C * t for t in targets]
    
    reduced = lll_reduction(bs)
    
    # Check rows for valid relations
    for row in reduced:
        coeffs = [int(round(x)) for x in row[:n]]
        
        # Check if coefficients are within bounds
        if all(abs(c) <= max_coeff for c in coeffs) and any(c != 0 for c in coeffs):
            # Verify relation
            error = sum(c * t for c, t in zip(coeffs, targets))
            if abs(error) < tolerance:
                return coeffs
                
    return None
